### ISSUE TITLE
Can we delete 3 files

### ISSUE THREAD

**Issue by 90barricade93** [90barricade93/WP_01_EC_AI_24Q2#3]
Hey team,

Can we now delete the following files:

ChefGPT_alessio.py
ChefGPY.py
innovative_dutch_chef.py

I want to double check this to be sure.

Thank you!

Regards,
Raymond

**Comment by AlessioChen** [comment]
yes we can do it. i will make a pull request

**Comment by 90barricade93** [comment]
ottimo lavoro!

**Comment by 90barricade93** [comment]
Deleted.
https://github.com/90barricade93/WP_01_EC_AI_24Q2/commit/b02adaa2aded4b30884adbd2ca355002ce5de218
