### ISSUE TITLE
Use of refactors branch

### ISSUE THREAD

**Issue by 90barricade93** [90barricade93/WP_01_EC_AI_24Q2#4]
Hey Alessio,

I had a question about using the branches in our repository. Are all team members supposed to use the refactors branch to commit changes? Or are there specific rules or guidelines we should follow when working with the main and refactors branches? What would you advise?

Thank you!

Regards,
Raymond

**Comment by AlessioChen** [comment]
We can make branches and then do pull requests or make a single develop branch where everyone pushes there.
But since it's a small project we can directly push to the main to make it easier :).
