### ISSUE TITLE
Possible "Overfitting" of Assignment

### ISSUE THREAD

**Issue by 90barricade93** [90barricade93/WP_01_EC_AI_24Q2#7]
Hi Alessio,

I am enjoying our work on the Chef GPT assignment, but I believe we may be "overfitting" the task. 
The original assignment was for each member to create their own Chef GPT script from scratch, using the lessons we have learned.

Do you agree with this approach, or should we consult neven for guidance?

Could we revert back to our original chefs, if necessary?

Best regards,
Raymond

**Comment by AlessioChen** [comment]
Sure we can revert, if necessary.

We can keep a script for everyone and let main.py as it is and update it to complete the tasks.

**Comment by 90barricade93** [comment]
yes, ok, let's try that.
i have added my chief to the src folder.
https://github.com/90barricade93/WP_01_EC_AI_24Q2/commit/89123654b3684843ede8c0df849061cb59f4a007
