### ISSUE TITLE
Weekend assignment submitted

### ISSUE THREAD

**Issue by 90barricade93** [90barricade93/WP_01_EC_AI_24Q2#8]
Hi all,

I have submitted the form with all our id's.
You can still add your own GPT chief and experiment.

I hope for next WP (weekend project) we find the time to communicate more often. 

I had fun exploring vision, image and text generation via OpenAI api.

We are going to dive in JS, time for me to refresh...
See you tonight!!

Best regards,
Raymond

**Comment by kshntn** [comment]
Hi Raymond, 
Thanks for the submission. I am unable to see the team in discord. It would be great if we can plan early on weekend.

**Comment by 90barricade93** [comment]
Hi Akash, 
I have already reported at neven from encode club that @AkashAntony don't seem to work in discord, i haven't heared from him yet. good to speak you!

**Comment by kshntn** [comment]
Hi Raymond, 
Could you please add me to the group as I am not able to see any discussion about the Bootcamp in the discord.

**Comment by 90barricade93** [comment]
I just tried to add you to group 9, neven did that also but somehow changed back...
